// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5DuKVKV--P2y2Ktv-02FhclxsfF2MPRE',
    appId: '1:802776261648:web:19146e1b86cd6cd5a61695',
    messagingSenderId: '802776261648',
    projectId: 'pas-service',
    authDomain: 'pas-service.firebaseapp.com',
    storageBucket: 'pas-service.appspot.com',
    measurementId: 'G-415CY3026N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_FcQlATR8MydLdZAjwPjvGwEE1Pqsw0',
    appId: '1:802776261648:android:0a2b72915fe9c093a61695',
    messagingSenderId: '802776261648',
    projectId: 'pas-service',
    storageBucket: 'pas-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPDqU2XCiWt8tVbhm7CQtPdrCXf0b-zhE',
    appId: '1:802776261648:ios:85673cd25df0e5b9a61695',
    messagingSenderId: '802776261648',
    projectId: 'pas-service',
    storageBucket: 'pas-service.appspot.com',
    iosBundleId: 'com.example.pasService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPDqU2XCiWt8tVbhm7CQtPdrCXf0b-zhE',
    appId: '1:802776261648:ios:ac470b069347202aa61695',
    messagingSenderId: '802776261648',
    projectId: 'pas-service',
    storageBucket: 'pas-service.appspot.com',
    iosBundleId: 'com.example.pasService.RunnerTests',
  );
}
